-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Budget Buddy v2, v16 by acgaruda@gmail.com **



-- ************************************** "Budget Buddy".Account

CREATE TABLE "Budget Buddy".Account
(
    account_id     int NOT NULL,
    name           varchar(50) NOT NULL,
    amount         decimal(10,2) NOT NULL,
    bank           varchar(50) NOT NULL,
    transaction_id int NOT NULL,
    CONSTRAINT PK_1 PRIMARY KEY ( account_id )
);


-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Budget Buddy v2, v16 by acgaruda@gmail.com **



-- ************************************** "Budget Buddy".Budget

CREATE TABLE "Budget Buddy".Budget
(
    budget_id    int NOT NULL,
    account_id   int NOT NULL,
    budget_name  varchar(50) NOT NULL,
    date_created timestamp NOT NULL,
    goals        varchar(50) NULL,
    group_id     int NOT NULL,
    CONSTRAINT PK_1 PRIMARY KEY ( budget_id ),
    CONSTRAINT FK_4 FOREIGN KEY ( group_id ) REFERENCES "Budget Buddy"."Group" ( group_id ),
    CONSTRAINT FK_7 FOREIGN KEY ( account_id ) REFERENCES "Budget Buddy".Account ( account_id )
);

CREATE INDEX FK_1 ON "Budget Buddy".Budget
    (
     group_id
        );

CREATE INDEX FK_2 ON "Budget Buddy".Budget
    (
     account_id
        );



-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Budget Buddy v2, v16 by acgaruda@gmail.com **



-- ************************************** "Budget Buddy".Category

CREATE TABLE "Budget Buddy".Category
(
    category_id int NOT NULL,
    name        varchar(50) NOT NULL,
    CONSTRAINT PK_1 PRIMARY KEY ( category_id )
);


-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Budget Buddy v2, v16 by acgaruda@gmail.com **



-- ************************************** "Budget Buddy".Category

CREATE TABLE "Budget Buddy".Category
(
    category_id int NOT NULL,
    name        varchar(50) NOT NULL,
    CONSTRAINT PK_1 PRIMARY KEY ( category_id )
);

-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Budget Buddy v2, v16 by acgaruda@gmail.com **



-- ************************************** "Budget Buddy".Transaction

CREATE TABLE "Budget Buddy".Transaction
(
    transaction_id int NOT NULL,
    account_id     int NOT NULL,
    amount         decimal(10,2) NOT NULL,
    currency       varchar(50) NOT NULL,
    category_id    int NOT NULL,
    identifier     varchar(50) NOT NULL,
    date_created   timestamp NOT NULL,
    CONSTRAINT PK_1 PRIMARY KEY ( transaction_id, account_id ),
    CONSTRAINT FK_6_1 FOREIGN KEY ( account_id ) REFERENCES "Budget Buddy".Account ( account_id ),
    CONSTRAINT FK_6 FOREIGN KEY ( category_id ) REFERENCES "Budget Buddy".Category ( category_id )
);

CREATE INDEX FK_1 ON "Budget Buddy".Transaction
    (
     account_id
        );

CREATE INDEX FK_2 ON "Budget Buddy".Transaction
    (
     category_id
        );


-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Budget Buddy v2, v16 by acgaruda@gmail.com **



-- ************************************** "Budget Buddy"."User"

CREATE TABLE "Budget Buddy"."User"
(
    user_id        int NOT NULL,
    username       varchar(50) NOT NULL,
    email          varchar(50) NOT NULL,
    name           varchar(50) NOT NULL,
    surname        varchar(50) NOT NULL,
    address_line_1 varchar(50) NULL,
    address_line_2 varchar(50) NULL,
    phone_no       varchar(50) NULL,
    budget_id      int NOT NULL,
    group_id       int NOT NULL,
    account_id     int NOT NULL,
    CONSTRAINT User_pk PRIMARY KEY ( user_id ),
    CONSTRAINT FK_1 FOREIGN KEY ( budget_id ) REFERENCES "Budget Buddy".Budget ( budget_id ),
    CONSTRAINT FK_2 FOREIGN KEY ( group_id ) REFERENCES "Budget Buddy"."Group" ( group_id ),
    CONSTRAINT FK_3 FOREIGN KEY ( account_id ) REFERENCES "Budget Buddy".Account ( account_id )
);

CREATE INDEX FK_1 ON "Budget Buddy"."User"
    (
     budget_id
        );

CREATE INDEX FK_2 ON "Budget Buddy"."User"
    (
     group_id
        );

CREATE INDEX FK_3 ON "Budget Buddy"."User"
    (
     account_id
        );



COMMENT ON COLUMN "Budget Buddy"."User".name IS 'Table saving data related to the user entity';