spring:
  application:
    name: "ubuntu-back-end"
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        driver-class-name: org.postgresql.Driver
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: budgetbuddy
      show_sql: false
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5433/Ubuntu_db?currenSchema=budgetbuddy
  flyway:
    enabled: false