spring:
  application:
    name: "ubuntu-back-end"
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        driver-class-name: org.postgresql.Driver
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: budgetbuddy
      show_sql: false
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5433/Ubuntu_db?currenSchema=budgetbuddy
  flyway:
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8084/realms/BudgetBuddy

keycloak:
  realm: Budgetbuddy
  authServerUrl: http://localhost:8084
  resource: budgetbuddy-system-client
  credentials:
    secret: 0iKRgUQveN4UiuPd0otOwxEyomQAIZSu
  clientId: budgetbuddy-system-client
  adminUsername: admin
  adminPassword: admin
  serverUrl: http://localhost:8084
