# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Build

on:
  push:
    paths:
      - 'ubuntu-back-end/**'
  pull_request:
    paths:
      - 'ubuntu-back-end/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Using the checkout action

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Check working directory
      run: pwd  # Run a shell command to check the current directory

    - name: List directory structure
      run: ls -R  # List the directory structure for debugging

    - name: Build with Maven
      run: mvn -B package --file ubuntu-back-end/pom.xml  # Run Maven with the correct pom.xml path

